### ISSUE TITLE
Always receiving Cannot read property 'src' / 'url' of undefined

### ISSUE THREAD

**Issue by oimlog** [quasibit/eleventy-plugin-schema#1]
I tried to use the plugin; however, I get the following error and have no idea why it is thrown. I simply installed the pluging, followed working examples of metadata.js, and restarted. Any help would be appreciated. Thanks.

`TemplateWriterWriteError` was thrown
> (./src/_includes/base.njk)
  Template render error: (C:\Users\admin\test\src\_includes\head.njk)
  EleventyShortcodeError: Error with Nunjucks shortcode `jsonLdScript`

`Template render error` was thrown
> Cannot read property 'src' of undefined

`Template render error` was thrown:
    TypeError: Cannot read property 'src' of undefined

**Comment by nunof07** [comment]
Hi @oimlog. I think an image might be missing. Can you try adding an image and see if it fixes?

![image](https://user-images.githubusercontent.com/13945913/125429005-e59b08b8-c04d-431d-8f24-5206a3585ac4.png)

**Comment by oimlog** [comment]
Nunof07,

Thank you, the src error has disappeared after applying what you suggested. However, the error has become the following:

Error writing templates: (more in DEBUG output)
> Having trouble writing template: output/index.html

`TemplateWriterWriteError` was thrown
> (./src/_includes/base.njk)
  Template render error: (C:\Users\admin\test\src\_includes\headPtn.njk)
  EleventyShortcodeError: Error with Nunjucks shortcode `jsonLdScript`

`Template render error` was thrown
> Cannot read property 'url' of null

`Template render error` was thrown:
    TypeError: Cannot read property 'url' of null

------
in base.njk, I've got the following, very simple:

type: page
meta:
	language: en-US
	title: "title"
	url: "{{ metadata.url }}"
	description: "description"
	image:
		src: http://localhost:8080/resource/img/test.png

**Comment by oimlog** [comment]
I also tried "http://localhost:8080/" instead of "{{ metadata.url }}" and it's still the same. Sorry, I'm kind of new to everything.

**Comment by nunof07** [comment]
@oimlog I think it's probably the site properties not being set.

Please make sure to set most properties from the example. I think only the logo is not required.

![image](https://user-images.githubusercontent.com/13945913/125489939-51cd4468-17bb-4887-8fe8-302b66f7bfa5.png)

**Comment by nunof07** [comment]
I'm going to close this. Let me know if you still have any issues.
