### ISSUE TITLE
WebPage publisher’s `url` should point to `#organization`

### ISSUE THREAD

**Issue by agarzola** [quasibit/eleventy-plugin-schema#29]
While working with this plugin I noticed that the `WebPage`’s `publisher` object is set to have `"url": "https://example.com"` instead of `"url": "https://example.com#organization"`, which is the proper `@id` for the `Organization` object. You can see this in the following line:

https://github.com/quasibit/eleventy-plugin-schema/blob/ec4f146641276b6447a8d891facb889d8feb6157/src/page.js#L50

I’ll submit a PR to address this shortly.

**Comment by nunof07** [comment]
Thank you @agarzola !
There were a couple of broken tests, but I've fixed them.

**Comment by agarzola** [comment]
@nunof07 I appreciate you handling those! I saw the email this morning about the broken builds and tried to make time to update my PR but just couldn’t make it happen today. I appreciate the assist!

**Comment by nunof07** [comment]
@agarzola all good, thank you.
