### ISSUE TITLE
Ability to output the JSON without the <script> tag

### ISSUE THREAD

**Issue by tfrancart** [quasibit/eleventy-plugin-schema#49]
Hi and thanks !

I'd like to output the raw JSON-LD in a separate output file (to process it as an RDF data file). For this I would like to output the JSON without the <script> tag around it. Would it be possible to add an option to do this ? (keeping the default behavior that keeps outputting the sript tag)

**Comment by nunof07** [comment]
Hi @tfrancart , I added a new shortcut that outputs without the script tag. It's called just `jsonLd`:

```
{% jsonLd meta, type, tags %}
```
