### ISSUE TITLE
[Discussion] What is the best schema layout?

### ISSUE THREAD

**Issue by christopherpickering** [quasibit/eleventy-plugin-schema#9]
I'm trying to get the biggest bang for my buck on schema. After browsing a lot of sites that have nice looking results on google, I think this kinda sums it up. What do you think about this being a good schema base?

## Optional Schemas for all pages
- [x] { Organization }, > for homage/about/contact. probably 1 page per site
- [x] { WebSite } + { SiteSearch },
- [x] { WebPage },
- [x] { BreadCrumbList },
- [ ] { SiteLinks } > can't find any useful info on this

## For a basic webpage
 - include the basics

## For a product (in addition to the basics)

- [x] { Product },
- [x]  { AggregateRating },
- [x]  { Review },
- [x]  { Offer }

## For a post (in addition to the basics, replace webpage)

- [x] { BlogPost }

## FAQ Page (in addition to the basics, replace webpage)

- [x] { FAQPage }

I use one "giant" meta that has all available fields listed, then on my pages select what type it is.

```js
module.exports = {
    type: data => data.type || "page",
    meta: {
      site: {
        name: data => data.site.name,
        description: data => data.site.description,
        url: data => data.site.url,
        logo: {
          src: data => data.site.url + data.site.image,
        }
      },
      language: data => "en-US",
      url: data => data.site.url + data.permalink,
      title: data => data.name || data.site.description + " | " + data.site.name,
      name: data => data.name,
      description: data => data.description || data.site.description,
      color: data=> data.color,
      brand: data=> data.publisher,
      manufacturer: data=> data.publisher,
      material: data => data.material,
      gtin13: data => data.isbn,
      productID: data => "ISBN:" + data.isbn,
      sku: data => data.sku,
      image: {
        src: data => data.site.url + data.site.image || data.image
       },
      rating: {
         ratingValue: data => data.rating || 0,
         bestRating: 5,
         worstRating: 0,
         ratingCount: data => data.ratingCount || 0
      },
      offers: {
         url: data => data.site.url + data.permalink,
         priceCurrency: "USD",
         price: data => data.price != undefined ? data.price.replace(/[^\d.]/g,'') : "",
         availability: "https://schema.org/InStock",
         priceValidUntil: (new Date(new Date().getFullYear(),12,0)).toISOString(),
         availabilityStarts: (new Date(new Date().getFullYear(),1,0)).toISOString(),
         // availabilityEnds: (new Date(new Date().getFullYear(),12,0)).toISOString(),
         itemCondition: "https://schema.org/NewCondition"
      },
     keywords: data => data.keywords
    }
};
```
I think we need to add organization, image, crumbs, links and search schemas to the base implementation. What do you think?

**Comment by nunof07** [comment]
Great summary. Don't know much beyond the basics, but what you said I think makes sense.

**Comment by christopherpickering** [comment]
I think this is all covered now! Thanks for fixing my poor js :)

**Comment by nunof07** [comment]
Thank you for all the work @christopherpickering!
